import '../styles/style.scss';

import $ from 'jquery';
import '../pug/blocks/input-dropdown/input-dropdown';
import '../pug/blocks/input/input-birthdate';
import '../pug/blocks/datepicker/datepicker-library';
import '../pug/blocks/datepicker/datepicker';
import '../pug/blocks/input-email/input-email';
import '../pug/blocks/button-like/button-like';
import '../pug/blocks/button-rate/jquery.star.rating';
import '../pug/blocks/button-rate/button-rate';
import '../pug/blocks/slide/jquery-ui.min';
import '../pug/blocks/slide/jquery.ui.touch-punch.min';
import '../pug/blocks/slide/slide';
import '../pug/blocks/button-submit/button-submit';
import '../pug/blocks/pagination/jquery.simplePagination';
import '../pug/blocks/pagination/pagination';
import '../pug/blocks/checkbox/checkbox';
import '../pug/blocks/card-photo/jquery.flexslider';
import '../pug/blocks/card-photo/card-photo';
import '../pug/blocks/header/header';
import '../pug/blocks/nav-link/nav-link';
import '../pug/blocks/main/slider';
import '../pug/blocks/main/main';
